//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace election_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalListCandidates
    {
        public int CandidateID { get; set; }
        public string CandidateName { get; set; }
        public string NationalNumber { get; set; }
        public string Governorate { get; set; }
        public string ElectionArea { get; set; }
        public Nullable<int> NumberOfVotesCandidate { get; set; }
        public Nullable<int> LocalListingID { get; set; }
    
        public virtual LocalList LocalList { get; set; }
    }
}
